specfile_path: v2rayN.spec
upstream_package_name: v2rayN
downstream_package_name: v2rayN
update_release: false

jobs:
  - job: copr_build
    trigger: release
    owner: repobot
    project: v2rayN
    targets:
      - almalinux-10-x86_64_v2
      - epel-10-x86_64
      - epel-10-aarch64
      - epel-10-ppc64le
      - rhel-10-x86_64
      - rhel-10-aarch64
      - rhel-10-ppc64le
      - rhel+epel-10-x86_64
      - rhel+epel-10-aarch64
      - rhel+epel-10-ppc64le
      - fedora-44-x86_64
      - fedora-43-x86_64
      - fedora-44-aarch64
      - fedora-43-aarch64
      - fedora-44-ppc64le
      - fedora-43-ppc64le
      - fedora-44-riscv64
      - fedora-43-riscv64
